ACTIVATOR_CLASS = "Activator"

BLOCK_TIMEOUT = 1000.0

FRAMEWORK_INACTIVE_STARTLEVEL = 0
FRAMEWORK_DEFAULT_STARTLEVEL = 1
SYSTEMBUNDLE_DEFAULT_STARTLEVEL = 0
BUNDLE_DEFAULT_STARTLEVEL = 1

FRAMEWORK_STARTLEVEL_PROP = "odss.framework.startlevel.begining"
BUNDLE_STARTLEVEL_PROP = "odss.framework.startlevel.bundle"
